set FASTFILTER_DIR=../fastfilter_java/bin
set FASTFILTER_FPFS=../fastfilter_fpfs/bin
set GUAVA_DIR=../../libs/guava-30.1.1-jre.jar

set CLASSPATH=./bin;%FASTFILTER_FPFS%;%FASTFILTER_DIR%;%GUAVA_DIR%

java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_f16.log

java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\NombresFPU2020.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_f16.log

REM Spanish representatives, active at the moment of the paper
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dactive_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dactive_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dactive_f16.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dactive_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dactive_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosCongresoActivos.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dactive_f16.log

REM Spanish representatives since 1970s
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dall_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dall_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Names.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\1000Surnames.txt" 0 > names_dall_f16.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 8 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dall_f8.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 12 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dall_f12.log
java -cp %CLASSPATH% org.fastfilter.xor.bbPrivacy.tester.NameSurnameBlackBoxTester 1000 16 "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\DiputadosTodasLegislaturas.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allNames.txt" "C:\Users\Alfonso\Documents\University\Research\Code\java\eclipse-workspace\SetConcentrationPrivacy\data\allSurnames.txt" 1 > names_random_dall_f16.log
